name: Selenium Grid Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium-hub:
        image: selenium/hub:4.20.0
        ports:
          - 4444:4444

      chrome:
        image: selenium/node-chrome:4.20.0
        depends_on: [selenium-hub]
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443

      firefox:
        image: selenium/node-firefox:4.20.0
        depends_on: [selenium-hub]
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Selenium Grid
        run: |
          until curl -s http://localhost:4444/status | grep -q '"ready":true'; do
            echo "Waiting for Selenium Grid..."
            sleep 3
          done

      - name: Run tests
        run: pytest -v test_grid.py
        env:
          GRID_URL: http://localhost:4444/wd/hub

