name: Selenium Grid Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    services:
      selenium-hub:
        image: selenium/hub:4.20.0
        ports:
          - 4442:4442
          - 4443:4443
          - 4444:4444
      chrome:
        image: selenium/node-chrome:4.20.0
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      firefox:
        image: selenium/node-firefox:4.20.0
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest pytest-xdist

      - name: Wait for Grid to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:4444/status | grep -q '"ready":true'; then
              echo "Grid is ready"
              break
            fi
            echo "Waiting for Selenium Grid..."
            sleep 2
          done

      - name: Run Selenium Grid tests
        run: pytest -n 2 -v

